# Generated by Django 5.2.4 on 2025-07-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kitapmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitapModel',
        ),
    ]
